server:
  port: 8088
spring:
  application:
    name: local-client

grpc:
  client:
# gRPC配置的名字，GrpcClient注解会⽤到
    local-grpc-server:
# gRPC服务端地址
      address: 'static://127.0.0.1:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
