# 开发环境
spring:
  datasource:
    druid:
      first:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://162.14.78.202:3306/metadata_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 201617wjy
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 25
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
        login:
          loginUsername: root
          loginPassword: root

      second:
        driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
        jdbc-url: jdbc:clickhouse://162.14.78.202:8123/Ticket_info
        username: default
        password: root
        initialSize: 10
        maxActive: 10000
        minIdle: 10
        maxWait: 60000

#swagger 开关
swagger:
  enable: true
  production: false
  basic:
    enable: false
    username: root
    password: 123456789
